---
- name: Creation utilisateur et configuration SSH
  hosts: webservers
  become: yes

  tasks:
    - name: Creer utilisateur devops avec un bash
      user:
        name: devops
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Ajouter la cle publique SSH pour devops
      authorized_key:
        user: devops
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
